name: 🤖 Revisión de Código con IA Claude

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  revision-ia:
    runs-on: ubuntu-latest
    name: Revisión de Código con IA

    steps:
      - name: 📥 Descargar Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 Análisis de Código con IA
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');

            try {
              // Obtener archivos modificados
              const changedFiles = execSync(`git diff --name-only origin/${{ github.base_ref }}...HEAD`, {encoding: 'utf8'})
                .trim().split('\n').filter(f => f);

              console.log(`Analizando ${changedFiles.length} archivos modificados`);

              let reviewBody = `## 🤖 Revisión de Código con IA Claude\n\n`;
              reviewBody += `**Archivos Modificados:** ${changedFiles.length}\n`;
              reviewBody += `**PR:** ${context.payload.pull_request.title}\n`;
              reviewBody += `**Autor:** @${context.payload.pull_request.user.login}\n\n`;

              // Análisis simple
              let problemas = [];
              const fs = require('fs');

              for (const file of changedFiles) {
                if (!fs.existsSync(file)) continue;

                try {
                  const content = fs.readFileSync(file, 'utf8');
                  const lines = content.split('\n');

                  lines.forEach((line, index) => {
                    const trimmed = line.trim();
                    const lineNum = index + 1;

                    // Detección de console.log
                    if (trimmed.includes('console.log')) {
                      problemas.push(`🔍 Declaración de debug en \`${file}:${lineNum}\` - \`${trimmed}\``);
                    }

                    // Detección de tipo any
                    if (trimmed.includes(': any')) {
                      problemas.push(`⚠️ Uso de tipo any en \`${file}:${lineNum}\` - \`${trimmed}\``);
                    }

                    // Detección de TODOs
                    if (trimmed.includes('TODO') || trimmed.includes('FIXME')) {
                      problemas.push(`📝 Deuda técnica en \`${file}:${lineNum}\` - \`${trimmed}\``);
                    }
                  });
                } catch (error) {
                  console.log(`No se pudo analizar ${file}: ${error.message}`);
                }
              }

              // Construir revisión
              if (problemas.length > 0) {
                reviewBody += `### 🚨 Problemas Encontrados (${problemas.length})\n\n`;
                problemas.slice(0, 10).forEach(problema => {
                  reviewBody += `- ${problema}\n`;
                });
                if (problemas.length > 10) {
                  reviewBody += `\n... y ${problemas.length - 10} problemas más\n`;
                }
              } else {
                reviewBody += `### ✅ No Se Encontraron Problemas\n\n¡Excelente trabajo! No se detectaron problemas obvios.\n`;
              }

              reviewBody += `\n### 📂 Archivos\n\n`;
              changedFiles.forEach(file => {
                reviewBody += `- \`${file}\`\n`;
              });

              reviewBody += `\n---\n*🤖 Revisión automatizada por IA Claude*`;

              // Publicar comentario
              await github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: reviewBody
              });

              console.log('✅ ¡Revisión publicada exitosamente!');

            } catch (error) {
              console.error('❌ La revisión falló:', error);

              // Publicar comentario de error
              await github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🤖 Revisión de Código con IA Claude\n\n❌ **La revisión falló debido a un error técnico**\n\nPor favor revisa los logs del workflow para más detalles.\n\n*🤖 Revisión automatizada por IA Claude*`
              });
            }